version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - ./test-config:/config
      - ./melcloud:/config/custom_components/melcloud
    environment:
      - TZ=America/New_York
